name: Test CI CD
on:
  push:
    branches: [main]
jobs:
  test-and-coverage-package:
    runs-on: ubuntu-latest
    env:
      COVERAGE_HTML_REPORT_PATH: /tmp/coverage_html_report
      COVERAGE_XML_REPORT_PATH: /tmp/coverage_xml_report.xml
      PYTEST_REPORT_PATH: /tmp/pytest_report.html
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: "Install project dependencies"
        run: pip install -r requirements.txt
      - name: "Run tests and code coverage analysis"
        run: coverage run -m pytest --html=${{ env.PYTEST_REPORT_PATH }} --self-contained-html
      - name: "Generate code coverage html report"
        run: coverage html --directory ${{ env.COVERAGE_HTML_REPORT_PATH }}
      - name: "Archive pytest and coverage reports"
        uses: actions/upload-artifact@v3
        if: ${{!cancelled()}}
        with:
          name: "Test and coverage reports"
          path: |
            ${{ env.PYTEST_REPORT_PATH }}
            ${{ env.COVERAGE_HTML_REPORT_PATH }}
      - name: "Generate code coverage xml report"
        run: coverage xml -o ${{ env.COVERAGE_XML_REPORT_PATH }}
      - name: "Push coverage xml report to codacy"
        uses: codacy/codacy-coverage-reporter-action@v1
        if: ${{!cancelled()}}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}
          coverage-reports: ${{ env.COVERAGE_XML_REPORT_PATH }}

  publish-package-as-artifact:
    needs: ["test-and-coverage-package"]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Publish package as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "Built package"
          path: "src"
